# General  
finetune: False
partial_train: null

# Traning 
epochs: 100
batch_size: 64 
lr_backbone: 0.0001
lr_head: 0.0001
weight_decay: 0.01
lr_decay: 0.95

# Model
with_emg_feat: False
backbone: DSTformer
num_joints: 17
maxlen: 1

model_version: class
dim_feat: 512
mlp_ratio: 2
depth: 5
dim_rep: 512
num_heads: 8
att_fuse: True 
hidden_dim: 2048
dropout_ratio: 0.5

# Data
dataset: cuhkx
action_classes: 44

# Augmentation
random_move: True
scale_range_train: [1, 3]
scale_range_test: [2, 2]